// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGcLBeTQtmebxV3YjV7Z9oBx25l_J6p0',
    appId: '1:360718300653:web:e8f14f654e7339fddd63e4',
    messagingSenderId: '360718300653',
    projectId: 'bootcampmaterial-f9300',
    authDomain: 'bootcampmaterial-f9300.firebaseapp.com',
    storageBucket: 'bootcampmaterial-f9300.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMP6PzGjdezVSbZ9LUt7b2HO04sva0nww',
    appId: '1:360718300653:android:c1e2824ea55e2cacdd63e4',
    messagingSenderId: '360718300653',
    projectId: 'bootcampmaterial-f9300',
    storageBucket: 'bootcampmaterial-f9300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyH6ehSMQ78QqoxDKQ0FJC2091l8du43I',
    appId: '1:360718300653:ios:4c97546b86b4cb48dd63e4',
    messagingSenderId: '360718300653',
    projectId: 'bootcampmaterial-f9300',
    storageBucket: 'bootcampmaterial-f9300.appspot.com',
    iosClientId: '360718300653-nk38nrj6qf3bh0nve41tnes18d9tp6sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyH6ehSMQ78QqoxDKQ0FJC2091l8du43I',
    appId: '1:360718300653:ios:4c97546b86b4cb48dd63e4',
    messagingSenderId: '360718300653',
    projectId: 'bootcampmaterial-f9300',
    storageBucket: 'bootcampmaterial-f9300.appspot.com',
    iosClientId: '360718300653-nk38nrj6qf3bh0nve41tnes18d9tp6sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
